# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Actions

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Runing Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Package Version Check Action
        uses: technote-space/package-version-check-action@v1.5.2
      - name: Install
        run: npm install
      - name: Test
        run: npm test
